the-ethan-hunt/first-timers-guide

Security/Steganography.md
I have written an article about Steganography in reference to issue #3 i.e, Add Steganography
=> Fix-issue #3

guides/Visual_design/Wireframing/Justinmind.md, guides/Visual_design/Wireframing/Wireframing.md
Added -
* Visual_design folder
* Wireframe folder
* Wireframe.md
* Justinmind.md
NOTE:
> Y
> Y
Written by myself.
=> Issue #22 - Wireframing

guides/Game Development/Unity.md
NOTE:
> Y
> Y
> Written myself
=> Issue #2 - Unity

guides/Game Development/Blender.md
NOTE:
> Y
> Y
> Written myself based on knowledge from a course taken at the University of Manchester (Sound and Digital Entertainment Technologies with Ricardo Climent).
=> issue #30 Create Blender entry

guides/Security/Wireshark.md
Added Wireshark article
NOTE:
> Y
> Y
Own words.
=> Added Wireshark.md #35

guides/data_science/natural_language_processing/stemming_lemmatization.md
First draft
NOTE:
> **Y**/N
> **Y**/N
> I wrote the article myself. Sources include the following:
https://nlp.stanford.edu/IR-book/html/htmledition/stemming-and-lemmatization-1.html
https://stackoverflow.com/questions/1787110/what-is-the-true-difference-between-lemmatization-vs-stemming
=> Information about stemming and lemmatization

guides/logic/The_Dining_Philosophers_Problem.md
#15 NOTE:
> Y
> Y
> Yes, I've written this article in my own words after taking inspiration from [Youtube](https://www.youtube.com/watch?v=NbwbQQB7xNQ&t=29s) & [Wikipedia](https://en.wikipedia.org/wiki/Dining_philosophers_problem)!
=> Issue #15, The Dining Philosophers Problem

guides/Visual_design/color theory/color theory.md
NOTE:
> Y
> Y
> [I have written this article myself though I have taken some reference from youtube videos for the color wheel part  ]
=> added color theory in visual design

guides/agile/Code_Smell.md
#9 NOTE:
> Y
> Y
> I've written this article mostly by myself and taken inspiration from [wikipedia](https://en.wikipedia.org/wiki/Code_smell)!
=> Issue #9, Code Smell

guides/web_development/NodeJS.md
NOTE:
> Yes
> Yes
> Written it from my own experience
=> Issue #63 added article on Node JS

guides/DevOps/docker_intro.md
NOTE:
> Y
> Y
> I watched this [YouTube](https://www.youtube.com/watch?v=lcQfQRDAMpQ&t=872s) video and then wrote the article in my own words.
=> Added Docker Part 1

guides/data_science/natural_language_processing/Text_Classification.md
#4 NOTE:
> Y
> Y
> Yes, I've written this article by myself & also took inspiration from all of youtube, wikipedia, blog posts, jounals & quora!
=> Issue #4, Text_Classification

guides/Cloud_development/Azure.md
NOTE:
> Y
> Y
> [I've written the article , i took information/help from the youtube videos , Wikipedia and some articles]
=> Updated PR for Azure article

guides/data_science/machine_learning/Regression.md
> Yes
> Yes
> Yes, I wrote it myself.
#51
=> Regression Introduction  #51

guides/Version_Control/svn.md
NOTE:
> Yes
> Yes
> I have written from my own experience
=> issue #78  Added SVN 

guides/DevOps/Ansible.md
NOTE:
> Y
> Y
> [I have taken inspiration from youtube videos for working of Ansible part.]
=> added Ansible in DevOps

guides/web_development/WebAssembly.md
#86 NOTE:
> Y
> Y
> I've written article this by myself but I've also taken inspiration from various online resources!
=> Issue #86, WebAssembly

guides/web_development/Reactjs.md
NOTE:
> Y
> Y
> Yes I have written this article solely from my own experience.
=> Issue #60 Reactjs starter guide

guides/DevOps/Vagrant.md
NOTE:
> Y
> Y
> [I have taken the references from various resources these are [A simple introduction to vagrant](https://opensource.com/resources/vagrant),[Vagrant docs](https://www.vagrantup.com/docs/),[drupal](https://www.drupal.org/node/2008794) ]
=> Added guide for vagrant

guides/agile/Software_Development_Life_Cycle.md
#94 NOTE:
> Y
> Y
> I've taken inspiration from various online resources but completely written it by myself!
=> Issue #94, SDLC

guides/Web_Frameworks/Angular.md
NOTE:
> Yes
> Yes
> [I have written this myself with the experience i had in angular. ]
=> add Angular

guides/Version_Control/svn.md
NOTE:
> Y
> Y
> I did not write any of the article myself accept for a few grammar changes and one spelling change. This is my first pull request outside of the first tutorial provided by GitHub. This seemed like a good place to try a simple pull request.
=> A few grammar and spelling changes.

Mongo DB/mongodb.md
NOTE:
y
y
> Y/N
> Y/N
Yes I took inspiration from youtube and Quora!!
=> issue#99,MongoDB

guides/Web_Frameworks/Drupal.md
NOTE:
> Y
> Y
> [I have taken reference of [Drupalize](https://drupalize.me/),[Drupal documentation](https://www.drupal.org/docs/8)]
=> Added guide for drupal

guides/DevOps/Laravel.md
#102 NOTE:
> Y
> Y
> Yes, I've taken inspiration from various online resources before writing the articles in my own words!
=> Issue #102, Laravel

guides/Web_Frameworks/Pheonix.md
NOTE:
> Y
> Y
> [I have taken reference from other resources [guide 1](http://phoenixframework.org/),[guide 2](https://medium.com/@elviovicosa/5-reasons-you-should-use-phoenix-instead-of-rails-in-your-next-project-504b4d83c48e),[guide 3](https://github.com/phoenixframework/phoenix)]
=> Added guide for Pheonix

guides/Game Development/Godot.md
NOTE:
> Y
> Y
> [I have taken inspiration from youtube and wikipedia ]
=> Added Godot

guides/data_science/data_visualization/D3.md
#110 NOTE:
> Y
> Y
> I've written it myself after taking inspiration from online resources!
=> Issue #110, D3.js

guides/Visual_design/Data visualisation/plotly.md, guides/Web_Frameworks/Pheonix.md
NOTE:
> Y
> Y
> [I have taken the reference from [wikipedia](https://en.wikipedia.org/wiki/Plotly), and [analytics vidhya](https://www.analyticsvidhya.com/blog/2017/01/beginners-guide-to-create-beautiful-interactive-data-visualizations-using-plotly-in-r-and-python/) ]
=> Added guide for plotly

guides/Web_Frameworks/Phalcon.md
NOTE:
Y
> Y/N
Y
Y
> Y/N
I TOOK INSPIRATION FROM VARIOUS SOURCES WHICH INCLUDES WIKIPEDIA QUORA
=> ISSUE#119 PHALCON

guides/Web_Frameworks/Grails.md
NOTE:
> Yes
> Yes
> [I've written in my words, took inspiration from youtube, and official docs]
=> add guide to grails

guides/logic/Turing_Test.md
#125 NOTE:
> Y
> Y
> I've taken inspiration from various online resources & then written it in my own words!
=> Issue #125, Turing Test

guides/data_science/data_visualization/Tableau.md
NOTE:
> Y
> Y
> [Yes I have taken inspiration from youtube and wikipedia ]
=> added  Tableau

guides/Visual_design/Architectural_Pattern/MVC.md
#135 NOTE:
> Y
> Y
> I've written it completely by myself.
=> Issue #135, MVC architectural pattern

guides/Version_Control/Mercurial.md
NOTE:
> Y
> Y
> [I have taken reference from [wikipedia](https://en.wikipedia.org/wiki/Mercurial) and [official guide](https://www.mercurial-scm.org/guide)]
=> added guide for mercurial

guides/data_science/Hidden Markov Model.md
NOTE:
> Y
> Y
> [yes I have taken inspiration from various sources like quora,youtube and wikipedia]
=> added Hidden Markov Model

vue-mat.md
NOTE:
> Y
> Y
> I referred https://vuematerial.io/getting-started to learn Vue Material by myself and I am writing this article after creating two Vue Material Projects.
=> Salma is adding an article - First timers guide to Vue Material

guides/Visual_design/Design_Language/Material_Design.md
#142 NOTE:
> Y
> Y
>I've written this article by myself after going through material design specs & various other online resources.
=> Issue #142, Material Design

guides/Starters/Vanilla_js.md
=> Vanilla js

guides/Web_Frameworks/Next.js
NOTE:
> Y
> Y
> [I have the reference from [Next js guide](https://nextjs.org/learn/)]
=> Added guide for Next.js

guides/DevOps/Package_Manager.md
#151 NOTE:
> Y
> Y
> I've written this article by myself after researching & reviewing various online resources!
=> Issue #151, Package Manager

guides/Web_Frameworks/Pyramid.md
NOTE:
> Y
> Y
> [I have taken the reference from [documentation](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/introduction.html#)]
=> Added guide for Pyramid

guides/Programming_Paradigm/OOP/Prototypal_Inheritance.md
#161 NOTE:
- Please fill out the template below
> Y
> Y
> I've written this article by myself after reading various online resources!
=> Issue #161 Prototypal Inheritance

guides/data_science/data_visualization/DataHero.md
=> added DataHero

guides/computation/Amdahl's_law.md
=> ISSUE #165 Amdahl's law

guides/Version_Control/GitHubSSH.md
> Y
> Y
> Inspired by [Wikipedia](https://en.wikipedia.org/wiki/Secure_Shell) and [GitHub](https://help.github.com/articles/connecting-to-github-with-ssh/). Written in my on words.
=> Add ssh article

guides/Networking/Blockchain.md
#188 NOTE:
> Y
> Y
> Yes, I've written it by myself after reading various articles!
=> Issue #188 Blockchain

guides/Cloud_development/REST API.md
NOTE:
> Y
> Y
> [I have used the [quora link](https://www.quora.com/What-is-a-REST-API) to study it]
=> added REST API guide

guides/Web_Containers/Progressive_Web_Apps.md
#191 NOTE:
> Y
> Y
> Yes, I've written it completely by myself.
=> Issue #191 PWA

guides/Web Containers/Apache Tomcat.md
NOTE:
> Y
> Y
> [Yes I have taken inspiration from youtube and wikipedia]
=> added Apache Tomcat

guides/issue_tracking/Jira.md
NOTE:
> Y
> Y
> Written in own words, information gathered from the Jira website which is linked to within the article for further information.
=> Created Jira guide

guides/issue_tracking/Bugzilla.md
NOTE:
> Y
> Y
> I wrote this article by myself. However, I have taken inspiration from this [article](https://www.bugzilla.org/features/) here.
=> created Bugzilla guide

CONTRIBUTING.md, README.md
Reverts the-ethan-hunt/first-timers-guide#205
=> Revert "[WIP] Improve style and tone of CONTRIBUTING and README"

guides/databases/mysql.md
NOTE:
> Y
> Y
> Yes, I ahve tken inspiration from tutorials point and w3schools
=> Added article for MySQL

guides/databases/database_keys.md
> Y
> Y
> I have written this article by myself in my own words, using my knowledge from daily database use and factual corrections from Database System Concepts chapter 2 by A. Silberschatz et al.
=> Add new guide to database keys

guides/Networking/IP_adresses.md
> Y
> Y
> I have written this article by myself in my own words, with factual corrections from my notes from the CISCO Networking Academy CCNA course.
=> Add new guide to reading IPv4 addresses

guides/SOLID_design_principles/Dependency_Inversion_Principle.md, guides/SOLID_design_principles/Interface_Segregation_Principle.md, guides/SOLID_design_principles/Liskov_Substitution_Principle.md, guides/SOLID_design_principles/Open-Closed_Principle.md, guides/SOLID_design_principles/Single_Responsibility_Principle.md
NOTE:
> Y/N Yes
> Y/N Yes
> [Write here. Be specific.] I took inspiration from an online blog. All references are at the bottom of each article. I
=> Added articles about SOLID design principles

guides/computation/Amdahl's_law.md
NOTE:
> Y
> Y
> Editing article written by someone else
=> Fix typos and make formatting changes in Amdahl's law article

guides/Starters/Creating_md_files.md
NOTE:
> Y
> Y
> Yes I made a simple document about what a markdown file was and how to create one. I also included a link that I used as well as some sample text that I had cited from the recourse. This was my first pull request!
=> Added Creating MD files guide

guides/web_development/svelte.md
NOTE:
> Y/N  yes
> Y/N yes
>  i wrote it myself with aid of my article in medium about svelte . i also referred svelte official site to write this guide
=> added svelte.md svelte guide

index.html
=> added id's to paragraph so that links in content scroll down to position

guides/Starters/Vanilla_js.md
I went through the Vanilla JavaScript tutorial to fix the grammar and formatting, and make it easier to read.
**Changes:**
- **Fixed** grammar & spelling mistakes that were apparent throughout the file, mainly things like words using ALL CAPS, lack of spacing, and inconsistent formatting.
- **Added** an actual example.
- **Added** more resources to learn vanilla JS.
> **Yes**
> **Yes**
> **Yes**, however this is an edit of an existing article.
=> Overhauled the Vanilla JavaScript tutorial to be more clear and concise.

PULL_REQUEST_TEMPLATE.md, guides/Version_Control/Git and PR.md
NOTE:
> Y
> Y
It's a modification in the form of a new PR
Hope you would check it and ignore minor mistakes.
=> New PR with added SLOC as asked 

guides/Cloud_development/ZEIT.md
NOTE:
> Y
> Y
> I've written this article by myself and taken inspiration and main information from ZEIT offical website.
=> Added ZEIT article in cloud development

PULL_REQUEST_TEMPLATE.md, guides/Testing/testing_pyramid.md
NOTE:
> Y
> Y
> This is a summary of the concept of the testing pyramid as written about in the wonderful bood, The Way of the Web Tester: A Beginner's Guide to Automation by Jonathan Rasmusson.
=> added a file about the testing pyramid

guides/Web_Containers/GlassFish.md
a brief summary or overview of what the keyword 'GlassFish' should mean to a technical person
NOTE:
> Y/N
y
> Y/N
y
yes, i have tried to formulate the topic in from my understanding
=> add introduction for GlassFish

guides/agile/How_To_Brainstorm.md
NOTE:
> Y
> Y
> I wrote this short notice. We use it for our new team members. The goal is to stay short and tell juste the actions (without theory) to our team mates.
=> added a small description of one way how to animate brainstorming sessions

OS.md
NOTE:
> Y
> Y
> Yes, I've written this article myself. I used the book Operating System Concepts by Silberschatz, Galvin, Gagne for reference, but wrote the article in my own words.
=> Added an article about Operating Systems

guides/databases/DBMS.md
NOTE:
> Y
> Y
> Yes, I've written this article myself. I used the book Database System Concepts by Silberschatz, Korth, Sudarshan for reference, but wrote the article in my own words.
=> Added article on database management system
